import { NextRequest, NextResponse } from "next/server";

interface GenerateImageRequestBody {
  prompt: string;
  characterContext?: Record<string, string>;
}

interface HuggingFaceErrorResponse {
  error?: string;
  estimated_time?: number;
}

const CONTEXT_LABELS: Record<string, string> = {
  name: "Nome",
  age: "Idade",
  nationality: "Nacionalidade",
  personality: "Personalidade",
  height: "Altura",
  style: "Estilo/Estilo de roupa",
};

const ART_DIRECTION_PROMPT = `You are an illustrator specialized in expressive hand-drawn digital artwork.
For every request, generate the image with the following art direction unless the user explicitly overrides it:
STYLE
- High-quality hand-drawn digital illustration.
- Original Character (OC) aesthetic.
- Anime-inspired mixed with western indie/furry artist style.
- Clean, confident lineart with varied line weight.
- Soft cel shading combined with subtle painterly rendering.
- Vibrant but balanced colors.
- Soft ambient lighting with gentle highlights.
- Slightly exaggerated facial expressions for personality.
- Stylized anatomy with appealing proportions.
- Natural, dynamic poses with clear silhouette.
- Expressive eyes and subtle facial details.
- Visible brush texture to preserve a hand-drawn feel.
- Illustration should never resemble a 3D render, CGI, photorealism, or AI-generated glossy art.
QUALITY
- Professional concept art quality.
- Highly polished.
- Crisp linework.
- Consistent character design.
- Clean color separation.
- Appealing composition.
- Rich visual storytelling.
- High attention to small details.
CHARACTER DESIGN
- Prioritize unique and memorable OC designs.
- Clothing should be layered, fashionable, and visually interesting.
- Accessories should complement the character.
- Hair should have dynamic, stylized shapes.
- Strong personality conveyed through pose and expression.
COLOR
- Harmonious color palette.
- Warm, soft lighting.
- Gentle gradients.
- Pleasant contrast.
- Saturated accents without oversaturation.
BACKGROUND
- Simple painted background, soft gradients, or lightly detailed environments that do not distract from the character.
AVOID
- Photorealism.
- 3D rendering.
- Plastic or glossy skin.
- Hyper-realistic textures.
- Low-detail coloring.
- Flat lighting.
- Overly sharp AI look.
- Deformed anatomy.
- Generic anime rendering.
- Blurry lineart.
- Watermarks.
- Text.
- Logos.
- Signatures.
Always preserve the hand-crafted illustration aesthetic, making every image look like it was professionally drawn by an experienced digital artist rather than generated by AI.`;

const NEGATIVE_PROMPT =
  "nsfw, lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name, photorealistic, 3d render";

function hasStyleHint(prompt: string, characterContext?: Record<string, string>): boolean {
  if (characterContext?.style?.trim()) return true;
  const styleKeywords = /estilo|anime|realista|aquarela|pixel ?art|cyberpunk|gótico|fantasia|pintura|render|3d|cartoon/i;
  return styleKeywords.test(prompt);
}

function buildImagePrompt(prompt: string, characterContext?: Record<string, string>): string {
  const contextParts = characterContext
    ? Object.entries(characterContext)
      .filter(([, value]) => value && value.trim().length > 0)
      .map(([key, value]) => `${CONTEXT_LABELS[key] ?? key}: ${value.trim()}`)
    : [];

  const pieces: string[] = ["masterpiece, best quality, highly detailed"];
  if (prompt) pieces.push(prompt);
  if (contextParts.length > 0) pieces.push(`Personagem — ${contextParts.join(", ")}`);

  const userRequest = pieces.join(". ").trim();

  if (hasStyleHint(prompt, characterContext)) {
    return userRequest;
  }

  return `${ART_DIRECTION_PROMPT}\n\nRequest: ${userRequest}`;
}

export async function POST(request: NextRequest): Promise<NextResponse> {
  const apiToken = process.env.HUGGINGFACE_API_TOKEN;
  const model = process.env.HUGGINGFACE_IMAGE_MODEL ?? "cagliostrolab/animagine-xl-4.0";

  if (!apiToken) {
    return NextResponse.json({ error: "HUGGINGFACE_API_TOKEN não configurada" }, { status: 500 });
  }

  let body: GenerateImageRequestBody;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Corpo da requisição inválido" }, { status: 400 });
  }

  const hasContext = Boolean(
    body.characterContext && Object.values(body.characterContext).some((v) => v && v.trim().length > 0)
  );

  if (!body.prompt?.trim() && !hasContext) {
    return NextResponse.json({ error: "Envie um prompt ou preencha o checklist do personagem" }, { status: 400 });
  }

  const finalPrompt = buildImagePrompt(body.prompt?.trim() ?? "", body.characterContext);

  const provider = process.env.HUGGINGFACE_PROVIDER ?? "hf-inference";
  const url = `https://router.huggingface.co/${provider}/models/${model}`;

  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      inputs: finalPrompt,
      parameters: {
        negative_prompt: NEGATIVE_PROMPT,
        guidance_scale: 7,
        num_inference_steps: 28,
      },
    }),
  });

  const contentType = response.headers.get("content-type") ?? "";

  if (!response.ok || !contentType.includes("image")) {
    let message = "Falha ao gerar a imagem";
    try {
      const errorData: HuggingFaceErrorResponse = await response.json();
      if (errorData.error?.includes("loading")) {
        message = `O modelo está carregando, tenta de novo em uns ${Math.ceil(
          errorData.estimated_time ?? 20
        )}s`;
      } else if (errorData.error) {
        message = errorData.error;
      }
    } catch {
    }

    console.error(`Hugging Face (Animagine) respondeu ${response.status}: ${message}`);
    return NextResponse.json({ error: message }, { status: 502 });
  }

  const arrayBuffer = await response.arrayBuffer();
  const base64 = Buffer.from(arrayBuffer).toString("base64");
  const imageUrl = `data:${contentType};base64,${base64}`;

  return NextResponse.json({ imageUrl, text: null });
}